import type { FoodItem } from './scoring'

export const FOOD_DB: FoodItem[] = [
  // HIGH PROTEIN NON-VEG
  {
    id: '1', name: 'Chicken Tikka (250g)', restaurant: 'Moti Mahal',
    protein_g: 45, calories: 350, price_inr: 320, diet_type: 'non_veg',
    swiggy_query: 'chicken tikka moti mahal', confidence: 0.80,
    tags: ['high_protein', 'low_carb', 'grilled'],
    why: ['Fills most of your protein gap in one dish', 'Low calorie — under 400 kcal for dinner', 'High satiety, no late-night hunger'],
  },
  {
    id: '2', name: 'Tandoori Chicken Half', restaurant: 'Biryani Blues',
    protein_g: 38, calories: 290, price_inr: 280, diet_type: 'non_veg',
    swiggy_query: 'tandoori chicken biryani blues', confidence: 0.78,
    tags: ['high_protein', 'low_carb', 'grilled'],
    why: ['Dense protein, very low calories', 'Works as dinner or post-gym meal', 'Widely available in Gurgaon & Bangalore'],
  },
  {
    id: '3', name: 'Chicken Shawarma Plate', restaurant: 'Al-Bake',
    protein_g: 35, calories: 520, price_inr: 220, diet_type: 'non_veg',
    swiggy_query: 'chicken shawarma al bake', confidence: 0.72,
    tags: ['high_protein', 'filling', 'popular'],
    why: ['Protein + carbs — good post-gym meal', 'Under ₹250', 'Consistent portion sizes across outlets'],
  },
  {
    id: '4', name: 'Grilled Fish Fillet', restaurant: 'FreshMenu',
    protein_g: 40, calories: 320, price_inr: 380, diet_type: 'non_veg',
    swiggy_query: 'grilled fish fillet freshmenu', confidence: 0.75,
    tags: ['high_protein', 'low_fat', 'lean'],
    why: ['Lean protein, very low fat', 'High confidence macro estimate', 'Light on calories'],
  },
  {
    id: '5', name: 'Chicken Burrito Bowl', restaurant: 'The Bowl Company',
    protein_g: 42, calories: 610, price_inr: 349, diet_type: 'non_veg',
    swiggy_query: 'chicken burrito bowl company', confidence: 0.76,
    tags: ['high_protein', 'complete_meal'],
    why: ['High protein, one complete meal', 'Consistent macro estimates', 'Popular with similar users'],
  },
  {
    id: '6', name: 'Egg Bhurji (4 eggs) + Roti', restaurant: 'Local Cloud Kitchen',
    protein_g: 28, calories: 440, price_inr: 160, diet_type: 'non_veg',
    swiggy_query: 'egg bhurji roti', confidence: 0.70,
    tags: ['budget', 'protein', 'filling'],
    why: ['Best budget pick under ₹200', 'Solid protein-to-price ratio', 'Quick 20-min delivery average'],
  },
  {
    id: '7', name: 'Chicken Caesar Salad', restaurant: 'Salad Days',
    protein_g: 32, calories: 410, price_inr: 320, diet_type: 'non_veg',
    swiggy_query: 'chicken caesar salad days', confidence: 0.73,
    tags: ['high_protein', 'light', 'salad'],
    why: ['High protein, light calories', 'Works as late dinner', 'Good for fat loss days'],
  },
  {
    id: '8', name: 'Mutton Seekh Kebab (6pc)', restaurant: 'Barbeque Nation',
    protein_g: 36, calories: 380, price_inr: 340, diet_type: 'non_veg',
    swiggy_query: 'mutton seekh kebab barbeque nation', confidence: 0.68,
    tags: ['high_protein', 'low_carb', 'kebab'],
    why: ['Dense protein per piece', 'Low carb, good for fat loss', 'Consistent chain quality'],
  },
  {
    id: '9', name: 'Chicken Malai Tikka', restaurant: 'Punjab Grill',
    protein_g: 40, calories: 320, price_inr: 360, diet_type: 'non_veg',
    swiggy_query: 'chicken malai tikka punjab grill', confidence: 0.75,
    tags: ['high_protein', 'low_carb', 'grilled'],
    why: ['High protein, low calorie', 'Grilled — no deep-fry calories', 'High satiety'],
  },
  {
    id: '10', name: 'Boiled Egg Bowl (6 eggs)', restaurant: 'Healthy Habit',
    protein_g: 36, calories: 468, price_inr: 120, diet_type: 'non_veg',
    swiggy_query: 'boiled egg bowl', confidence: 0.90,
    tags: ['budget', 'high_protein', 'simple'],
    why: ['Best protein-per-rupee non-veg', 'Precise macro estimate — eggs are consistent', 'Great snack or light meal'],
  },
  {
    id: '11', name: 'Chicken Soup (large)', restaurant: 'Healthy Habit',
    protein_g: 30, calories: 220, price_inr: 180, diet_type: 'non_veg',
    swiggy_query: 'chicken soup healthy habit', confidence: 0.72,
    tags: ['high_protein', 'low_calorie', 'light'],
    why: ['Very low calories, solid protein', 'Good when calories are tight', 'Light on the stomach'],
  },
  {
    id: '12', name: 'Chicken Fried Rice (full)', restaurant: 'Chinese Wok',
    protein_g: 22, calories: 680, price_inr: 200, diet_type: 'non_veg',
    swiggy_query: 'chicken fried rice chinese wok', confidence: 0.65,
    tags: ['protein', 'comfort', 'carb_heavy'],
    why: ['Decent protein + filling carbs', 'Good when you need both macros', 'Budget-friendly'],
  },

  // HIGH PROTEIN VEG
  {
    id: '13', name: 'Paneer Tikka (300g)', restaurant: 'BBQ Nation Delivery',
    protein_g: 30, calories: 440, price_inr: 320, diet_type: 'veg',
    swiggy_query: 'paneer tikka barbeque nation', confidence: 0.77,
    tags: ['high_protein_veg', 'grilled'],
    why: ['Best grilled veg protein option', 'Good macro estimate from chain data', 'Substantial 300g portion'],
  },
  {
    id: '14', name: 'Paneer Bhurji + 2 Roti', restaurant: 'Sardar Ji da Dhaba',
    protein_g: 24, calories: 480, price_inr: 180, diet_type: 'veg',
    swiggy_query: 'paneer bhurji roti sardar', confidence: 0.70,
    tags: ['veg', 'protein', 'filling'],
    why: ['Budget protein pick under ₹200', 'Filling — good as main meal', 'Protein + carb combo'],
  },
  {
    id: '15', name: 'Soya Chunks Curry + Rice', restaurant: 'Homestyle Kitchen',
    protein_g: 26, calories: 520, price_inr: 160, diet_type: 'veg',
    swiggy_query: 'soya chunks curry rice', confidence: 0.65,
    tags: ['veg', 'budget', 'high_protein_veg'],
    why: ['Best protein-per-rupee veg option', 'High fibre, slow-digesting carbs', 'Under ₹200'],
  },
  {
    id: '16', name: 'Palak Paneer + 2 Roti', restaurant: 'Bikanervala',
    protein_g: 22, calories: 460, price_inr: 200, diet_type: 'veg',
    swiggy_query: 'palak paneer roti bikanervala', confidence: 0.72,
    tags: ['veg', 'protein', 'classic'],
    why: ['Classic balanced veg meal', 'Iron + protein from spinach and paneer', 'Consistent portion from chain'],
  },
  {
    id: '17', name: 'Tofu Stir Fry Bowl', restaurant: 'The Bowl Company',
    protein_g: 28, calories: 380, price_inr: 299, diet_type: 'veg',
    swiggy_query: 'tofu stir fry bowl company', confidence: 0.73,
    tags: ['veg', 'high_protein_veg', 'light'],
    why: ['High protein for a veg meal', 'Low calorie — good for fat loss', 'Fresh, clean macros'],
  },
  {
    id: '18', name: 'Rajma Chawal', restaurant: 'Sardar Ji da Dhaba',
    protein_g: 18, calories: 560, price_inr: 150, diet_type: 'veg',
    swiggy_query: 'rajma chawal sardar', confidence: 0.68,
    tags: ['veg', 'classic', 'comfort'],
    why: ['Comfort food with decent protein', 'High fibre, keeps you full', 'Very budget-friendly'],
  },
  {
    id: '19', name: 'Sprouts Salad Bowl', restaurant: 'Salad Days',
    protein_g: 18, calories: 280, price_inr: 240, diet_type: 'veg',
    swiggy_query: 'sprouts salad days', confidence: 0.72,
    tags: ['veg', 'light', 'fresh'],
    why: ['Very light — combine with a protein snack', 'Under 300 kcal', 'High fibre content'],
  },
  {
    id: '20', name: 'Dal Makhani + 2 Roti', restaurant: 'Punjab Grill',
    protein_g: 16, calories: 520, price_inr: 200, diet_type: 'veg',
    swiggy_query: 'dal makhani roti punjab grill', confidence: 0.70,
    tags: ['veg', 'classic', 'comfort'],
    why: ['Comfort meal with solid lentil protein', 'Good carb balance', 'Consistent chain portion'],
  },
  {
    id: '21', name: 'Greek Yogurt Bowl (400g)', restaurant: 'Healthy Habit',
    protein_g: 20, calories: 240, price_inr: 180, diet_type: 'veg',
    swiggy_query: 'greek yogurt bowl healthy habit', confidence: 0.82,
    tags: ['veg', 'light', 'protein_snack'],
    why: ['High confidence — packaged product', 'Good as a pre-sleep protein snack', 'Low calorie, high protein'],
  },
  {
    id: '22', name: 'Paneer Power Bowl', restaurant: 'The Bowl Company',
    protein_g: 28, calories: 510, price_inr: 280, diet_type: 'veg',
    swiggy_query: 'paneer power bowl company', confidence: 0.74,
    tags: ['veg', 'complete_meal', 'filling'],
    why: ['Best all-round veg protein meal', 'Filling — reduces late-night snacking', 'Good calorie-to-protein balance'],
  },

  // SNACKS / PROTEIN BOOSTERS
  {
    id: '23', name: 'Protein Shake (whey, 30g)', restaurant: 'GNC / Health Store',
    protein_g: 24, calories: 130, price_inr: 80, diet_type: 'non_veg',
    swiggy_query: 'protein shake whey', confidence: 0.95,
    tags: ['snack', 'protein_boost', 'quick'],
    why: ['Highest confidence estimate — labelled product', 'Fast-absorbing protein for post-gym', 'Lowest calorie-per-gram option'],
  },
  {
    id: '24', name: 'Chicken Tikka Roll', restaurant: 'Wrap Republic',
    protein_g: 26, calories: 420, price_inr: 160, diet_type: 'non_veg',
    swiggy_query: 'chicken tikka roll wrap republic', confidence: 0.71,
    tags: ['snack', 'protein', 'portable'],
    why: ['Quick protein top-up snack', 'Under ₹200', 'Portable — good between meals'],
  },
  {
    id: '25', name: 'Roasted Chana (200g)', restaurant: 'Local Snack Stall',
    protein_g: 20, calories: 380, price_inr: 60, diet_type: 'veg',
    swiggy_query: 'roasted chana', confidence: 0.85,
    tags: ['veg', 'snack', 'budget'],
    why: ['Best budget veg protein snack', 'High fibre keeps you full', 'Precise macro estimate — dry legume'],
  },

  // BREAKFAST
  {
    id: '26', name: 'Omelette (3 egg) + Brown Toast', restaurant: 'Local Café',
    protein_g: 22, calories: 380, price_inr: 120, diet_type: 'non_veg',
    swiggy_query: '3 egg omelette toast', confidence: 0.78,
    tags: ['breakfast', 'protein', 'classic'],
    why: ['Solid breakfast protein', 'Moderate carbs from toast', 'Budget-friendly morning option'],
  },
  {
    id: '27', name: 'Moong Dal Chilla (4pc)', restaurant: 'Healthy Habit',
    protein_g: 16, calories: 320, price_inr: 140, diet_type: 'veg',
    swiggy_query: 'moong dal chilla healthy habit', confidence: 0.75,
    tags: ['breakfast', 'veg', 'light'],
    why: ['Light high-protein breakfast', 'Good veg option for mornings', 'Low calorie, high fibre'],
  },
  {
    id: '28', name: 'Chicken Sandwich (double)', restaurant: 'Subway',
    protein_g: 30, calories: 540, price_inr: 280, diet_type: 'non_veg',
    swiggy_query: 'chicken sandwich subway', confidence: 0.80,
    tags: ['protein', 'filling', 'chain'],
    why: ['Consistent chain macros', 'Filling — good as lunch', 'Protein + carb combo'],
  },
  {
    id: '29', name: 'Paneer Paratha (2pc) + Curd', restaurant: 'Sardar Ji da Dhaba',
    protein_g: 18, calories: 520, price_inr: 160, diet_type: 'veg',
    swiggy_query: 'paneer paratha curd sardar', confidence: 0.68,
    tags: ['breakfast', 'veg', 'filling'],
    why: ['Classic North Indian breakfast', 'Protein from paneer + curd', 'Good when calories allow'],
  },
  {
    id: '30', name: 'Chicken Keema Omelette', restaurant: 'Local Cloud Kitchen',
    protein_g: 34, calories: 380, price_inr: 180, diet_type: 'non_veg',
    swiggy_query: 'chicken keema omelette', confidence: 0.72,
    tags: ['breakfast', 'high_protein', 'filling'],
    why: ['Double protein hit — egg + chicken', 'Great post-gym breakfast', 'Budget-friendly'],
  },
]
